# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Guglielmo Gemignani
email: guglielmogemignani@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal webpage describing projects of Guglielmo Gemignani
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://g-gemignani.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  g-gemignani

# Build settings
markdown: kramdown
remote_theme: pages-themes/hacker@v0.2.0
#theme: minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme # add this line to the plugins list if you already have one

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
