# Site settings
title: Guglielmo Gemignani
tagline: Head of Software, robotics and AI
author:
  name: Guglielmo Gemignani
  email: guglielmogemignani@gmail.com
  linkedin: https://www.linkedin.com/in/guglielmo-gemignani
  github: https://github.com/g-gemignani
  github_username: g-gemignani

description: >
  Software leader and researcher working on uncrewed aerial systems, autonomous robots, AI, and intelligent machine behavior.
url: "https://g-gemignani.github.io" # the base hostname & protocol for your site

# Build settings
exclude:
 - cv-source
markdown: kramdown
plugins:
 - jekyll-seo-tag
 - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      image: /img/og-image.jpg
